//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyxie.Plugin.Promotions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nyxie.Plugin.Promotions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string ContainsOperator {
            get {
                return ResourceManager.GetString("ContainsOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string EndsWithOperator {
            get {
                return ResourceManager.GetString("EndsWithOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to (case-incensitive).
        /// </summary>
        internal static string EqualityCaseInsensitiveOperator {
            get {
                return ResourceManager.GetString("EqualityCaseInsensitiveOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to.
        /// </summary>
        internal static string EqualityOperator {
            get {
                return ResourceManager.GetString("EqualityOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than or equal to.
        /// </summary>
        internal static string GreaterThanEqualToOperator {
            get {
                return ResourceManager.GetString("GreaterThanEqualToOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        internal static string GreaterThanOperator {
            get {
                return ResourceManager.GetString("GreaterThanOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (incl. sub-categories).
        /// </summary>
        internal static string IncludingSubCategories {
            get {
                return ResourceManager.GetString("IncludingSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than or equal to.
        /// </summary>
        internal static string LessThanEqualToOperator {
            get {
                return ResourceManager.GetString("LessThanEqualToOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        internal static string LessThanOperator {
            get {
                return ResourceManager.GetString("LessThanOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal to (case-incensitive).
        /// </summary>
        internal static string NotEqualityCaseInsensitiveOperator {
            get {
                return ResourceManager.GetString("NotEqualityCaseInsensitiveOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal to.
        /// </summary>
        internal static string NotEqualityOperator {
            get {
                return ResourceManager.GetString("NotEqualityOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least Expensive Products First.
        /// </summary>
        internal static string PriceAscending_DisplayName {
            get {
                return ResourceManager.GetString("PriceAscending_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Expensive Products First.
        /// </summary>
        internal static string PriceDescending_DisplayName {
            get {
                return ResourceManager.GetString("PriceDescending_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches regular expression.
        /// </summary>
        internal static string RegexOperator {
            get {
                return ResourceManager.GetString("RegexOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        internal static string StartsWithOperator {
            get {
                return ResourceManager.GetString("StartsWithOperator", resourceCulture);
            }
        }
    }
}
