---
ID: "a5f1ee3a-2ca2-4179-8f26-ea0e1fe25cb8"
Parent: "6ebe080e-fca4-4f48-ace3-f8dacc45c465"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/MyTenant/Storefront/Presentation/Rendering Variants/POI/Default
DB: master
BranchID: "0f31020c-79af-47c9-b8e6-c98720ae8a13"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{09180CD8-3CA2-4A92-B3B5-F4F057BA465C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190809T111958Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
