---
ID: "403cae88-2f43-4625-9ab2-80b6df821589"
Parent: "38cdbeb2-c6b5-49ad-a608-de1cc1337048"
Template: "aca5c9a3-cda0-49b6-893f-1d4a7cb595b0"
Path: /sitecore/content/MyTenant/Storefront/Presentation/Rendering Variants/Product Bundle/Default/Bundle Groups Container/Bundle Groups Reference/Bundle Group/Bundle Group Body Container/Product Link Container
DB: master
SharedFields:
- ID: "bea2740e-90d1-4b16-bd1d-7a7cc8605d2d"
  Hint: CssClass
  Value: "product-link-container"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181214T025655Z
